# Generated by Django 5.0.2 on 2024-02-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_portfolio_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.student'),
        ),
    ]
